### ISSUE TITLE
Restrict campaign creation for specific roles

### ISSUE THREAD

**Issue by imilchev** [podkrepi-bg/api#129]
The campaign creation endpoint is currently set to `Public` as can be seen [here](https://github.com/podkrepi-bg/api/blob/master/apps/api/src/campaign/campaign.controller.ts#L26). We should determine which roles are allowed to create a campaign and restrict the access.

I am not sure if it is intended but currently the campaign coordinator is an input from the front-end. I would actually expect this to be retrieved from the currently authenticated user instead of being a random input.

Note that after adjusting the roles allowed to create a campaign, the campaign files controller should be adjusted as well.

**Comment by Bunny303** [comment]
> I am not sure if it is intended but currently the campaign coordinator is an input from the front-end. I would actually expect this to be retrieved from the currently authenticated user instead of being a random input.

Is it decided or disscussed campaign coordinator to be currently authenticated user? Because at the moment in the create campaign form there is option coordinator to be different.

**Comment by Bunny303** [comment]
At the moment campaign coordinator is an input from the front-end, we want to change that and logged in user to be added as a coordinator. In order to achieve it next steps should be implemented:
- coordinatorId to be added internally from logged in user
- update of campaign to be restricted only to coordinator including campaign file uploads
- same person could be coordinator and beneficiary

**Comment by Bunny303** [comment]
Resolved in #207
