### ISSUE TITLE
Cloud API tests fail on PRs from forks

### ISSUE THREAD

**Issue by batebobo** [podkrepi-bg/api#370]
Observed in [https://github.com/podkrepi-bg/api/pull/369](https://github.com/podkrepi-bg/api/pull/369)

The specific error is that the generated coverage report is not accessible by the action - [https://github.com/podkrepi-bg/api/actions/runs/3566335063/jobs/5993345937](https://github.com/podkrepi-bg/api/actions/runs/3566335063/jobs/5993345937)

I'd expect CI runs not to depend on whether the PR is coming from a fork

**Comment by imilchev** [comment]
The tests create an HTML report with the results in the actual workflow. In order to do that you need repo permissions which a forked repository does not have. That is the reason why the reporting fails from a fork. The fix is to do the reporting from upstream instead of the fork. I will try to fix this today
